### ISSUE TITLE
503 on püb-portal http://tools.dcentproject.eu/

### ISSUE THREAD

**Issue by pflegende** [rbjarnason/your-priorities#16]
if somebody is watching the ptoject, coming from http://tools.dcentproject.eu/
and talking to:

Citizen priorities and budgeting
Participation platform for the city of Reykjavik

`Failed to resolve the name of server www.your-priorities-preview.org`

**Comment by rbjarnason** [comment]
@pflegende Thanks for letting us know, we had forgotten that this page has that very old link. We'll see if we can have it fixed. Here is the URL for the latest iteration of the live platform: https://yrpri.org/

**Comment by rbjarnason** [comment]
@pflegende This issue has now been resolved and the www.your-priorities-preview.org DNS name is now working.
